__author__ = "willy santiago solarte"
__license__ = "GPL"
__version__ = "1.0.0"
__email__ = "willy.solarte@campusucc.edu.co"

from SimuladorBancario import SimuladorBancario
class CDT:
    # aqui inicia la declaracion de mi clase
    """-----------------------------------------------
    # Atributos 
    -------------------------------------------------"""

    interes_simple=0
    interes_compuesto=0

    def Darsaldo(self):
        #aqui va el codigo
        return self.saldo
    